manifest-version = 1

[component]
name = "Mixpanel"
version = "1.2.0"
type = "data-collection"
language = "Rust"
category = "data-collection"
subcategory = "analytics"
description = """
# Mixpanel Component

[https://www.edgee.cloud/edgee/mixpanel](https://www.edgee.cloud/edgee/mixpanel)

## Overview

The **Mixpanel** component by Edgee enables server-side analytics by sending events, page views, and user profiles directly to Mixpanel's HTTP API from the edge.
Optimized for performance, it leverages Edgee's WebAssembly runtime to avoid traditional SDKs, ensuring fast and efficient data processing.

---

## Key Features & Benefits

### Features

- **Multi-Event Support**: Supports `track`, `page`, and `user` events.
- **Mixpanel API Integration**: Targets Mixpanel's `/import` and `/engage` endpoints.
- **Wasm Performance**: Built using Rust and compiled to WebAssembly for high performance.
- **Lightweight Deployment**: Minimal client-side dependencies.
- **Edgee Data Layer Ready**: Easy integration with Edgee's Data Layer.

### Benefits

- **Data Accuracy**: Enhanced data accuracy with server-side event processing.
- **Low Latency**: Reduced latency by processing data closer to the user.
- **Simplified Setup**: No need for complex SDKs or client-heavy configurations.
- **Scalability**: Improved scalability and maintainability.

---

## Use Cases

- **User Interaction Tracking**: Monitor and analyze user behavior and engagement.
- **Page View Analytics**: Capture page visits and navigation paths.
- **User Profile Management**: Track and update user attributes and sessions.
- **Edge Analytics**: Integrate Mixpanel in edge-first computing environments.

---

Additional resources: [Mixpanel Product Analytics Platform](https://mixpanel.com/)
"""
documentation = "https://github.com/edgee-cloud/mixpanel-component"
repository = "https://github.com/edgee-cloud/mixpanel-component"
wit-version = "1.0.0"
icon-path = "mixpanel.png"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && cp ./target/wasm32-wasip2/release/mixpanel.wasm ./mixpanel.wasm"
output_path = "mixpanel.wasm"

[component.settings.api_secret]
title = "Mixpanel Project API Secret"
type = "string"
required = true
description = "Your Mixpanel API Secret. You can get it in your project settings. Don't mistake it with the Project Token."
secret = true

[component.settings.project_token]
title = "Mixpanel Project Token"
type = "string"
required = true
description = "Used for Engage API to update user profiles. You can find it in your Mixpanel project settings. Don't mistake it with the API Secret."
secret = true

[component.settings.project_id]
title = "Mixpanel Project ID"
type = "string"
description = "Optional project ID for strict import validation. Used in the query string."

[component.settings.region]
title = "Mixpanel Project Region"
type = "string"
description = "Choose from: api, api-eu, or api-in"
required = false
options = ["api", "api-eu", "api-in"]