manifest-version = 1

[component]
name = "Mixpanel"
version = "1.2.0"
type = "data-collection"
language = "Rust"
category = "data-collection"
subcategory = "analytics"
description = """
This component lets you capture **events**, **page views**, and **user profiles** directly at the edge using [Mixpanel's HTTP API](https://developer.mixpanel.com/reference/overview).
Optimized and focused on performance, it avoids traditional SDKs by leveraging Edgee's WebAssembly runtime.

- Supports: `track`, `page`, `user`
- Targets: Mixpanel `/import` and `/engage` endpoints
- [Documentation & Source](https://github.com/edgee-cloud/mixpanel-component)
"""
documentation = "https://github.com/edgee-cloud/mixpanel-component"
repository = "https://github.com/edgee-cloud/mixpanel-component"
wit-version = "1.0.0"
icon-path = "mixpanel.png"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && cp ./target/wasm32-wasip2/release/mixpanel.wasm ./mixpanel.wasm"
output_path = "mixpanel.wasm"

[component.settings.api_secret]
title = "Mixpanel Project API Secret"
type = "string"
required = true
description = "Your Mixpanel API Secret. You can get it in your project settings. Don't mistake it with the Project Token."
secret = true

[component.settings.project_token]
title = "Mixpanel Project Token"
type = "string"
required = true
description = "Used for Engage API to update user profiles. You can find it in your Mixpanel project settings. Don't mistake it with the API Secret."
secret = true

[component.settings.project_id]
title = "Mixpanel Project ID"
type = "string"
description = "Optional project ID for strict import validation. Used in the query string."

[component.settings.region]
title = "Mixpanel Project Region"
type = "string"
description = "Choose from: api, api-eu, or api-in"
required = false
options = ["api", "api-eu", "api-in"]