name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: wasm32-wasi
      - name: Build component
        run: |
          cargo build --target wasm32-wasi --release
          cargo test
      - name: Build Wasm via Edgee CLI
        run: |
          curl -L https://install.edgee.cloud | sh
          ./edgee component build
